"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import { motion } from "framer-motion";
import { Stethoscope, User, Calendar, Download, Heart } from "lucide-react";
import { Button } from "@/components/ui/button";

interface PatientSummaryData {
  patient_name: string;
  doctor_name: string;
  summary: string;
  created_at: string;
  session_id: string;
}

export default function PatientSummaryPage() {
  const params = useParams();
  const sessionId = params.id as string;
  
  const [summaryData, setSummaryData] = useState<PatientSummaryData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (sessionId) {
      fetchSummaryData();
    }
  }, [sessionId]);

  const fetchSummaryData = async () => {
    try {
      const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/qr/summary/${sessionId}`);
      if (response.ok) {
        const data = await response.json();
        setSummaryData(data);
      } else if (response.status === 404) {
        setError("Your summary is being prepared. Please check back in a few minutes.");
      } else {
        setError("Summary not found or not available");
      }
    } catch (error) {
      console.error("Error fetching summary:", error);
      setError("Failed to load summary");
    } finally {
      setLoading(false);
    }
  };

  const downloadSummary = () => {
    if (!summaryData) return;
    
    const content = `
Medical Visit Summary
Patient: ${summaryData.patient_name}
Doctor: Dr. ${summaryData.doctor_name}
Date: ${new Date(summaryData.created_at).toLocaleDateString()}

${summaryData.summary}

---
Generated by Skribe - Smart Healthcare Dictation
    `.trim();
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `medical-summary-${summaryData.patient_name.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-500 mx-auto mb-4"></div>
          <p className="text-gray-400">Loading your medical summary...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 bg-red-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
            <Heart className="w-8 h-8 text-red-400" />
          </div>
          <h1 className="text-2xl font-bold text-white mb-2">Summary Not Available</h1>
          <p className="text-gray-400">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black text-white font-dm-sans">
      {/* Background Effects - Softer for patient view */}
      <div className="absolute inset-0 bg-gradient-to-br from-purple-900/10 via-black to-blue-900/10"></div>
      <div className="absolute inset-0 opacity-10" style={{
        backgroundImage: `
          linear-gradient(30deg, rgba(147, 51, 234, 0.05) 1px, transparent 1px),
          linear-gradient(150deg, rgba(59, 130, 246, 0.05) 1px, transparent 1px)
        `,
        backgroundSize: '80px 80px'
      }}></div>

      {/* Header */}
      <header className="relative z-10 border-b border-gray-800/30 backdrop-blur-xl">
        <div className="max-w-4xl mx-auto px-6 py-6">
          <div className="flex items-center justify-center">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 bg-gradient-to-br from-purple-500 via-purple-600 to-blue-600 rounded-2xl flex items-center justify-center shadow-lg">
                <Stethoscope className="w-6 h-6 text-white" />
              </div>
              <div className="text-center">
                <h1 className="text-2xl font-bold gradient-text-light">Medical Summary</h1>
                <p className="text-sm text-gray-400">Powered by Skribe</p>
              </div>
            </div>
          </div>
        </div>
      </header>

      <div className="relative z-10 max-w-4xl mx-auto px-6 py-8">
        {summaryData && (
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-8"
          >
            {/* Patient Info Card */}
            <div className="glass-dark rounded-2xl p-8 shadow-xl">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-4">
                  <div className="w-16 h-16 bg-gradient-to-br from-purple-500/20 to-blue-500/20 rounded-full flex items-center justify-center border border-purple-500/30">
                    <User className="w-8 h-8 text-purple-300" />
                  </div>
                  <div>
                    <h2 className="text-2xl font-bold text-white">{summaryData.patient_name}</h2>
                    <p className="text-gray-400">Patient Summary</p>
                  </div>
                </div>
                
                <Button
                  onClick={downloadSummary}
                  className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download Summary
                </Button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                <div className="bg-gray-800/30 rounded-lg p-4">
                  <p className="text-sm text-gray-400 mb-1">Healthcare Provider</p>
                  <p className="text-white font-semibold">Dr. {summaryData.doctor_name}</p>
                </div>
                
                <div className="bg-gray-800/30 rounded-lg p-4">
                  <p className="text-sm text-gray-400 mb-1">Visit Date</p>
                  <p className="text-white font-semibold flex items-center gap-2">
                    <Calendar className="w-4 h-4 text-purple-400" />
                    {new Date(summaryData.created_at).toLocaleDateString('en-US', {
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit'
                    })}
                  </p>
                </div>
              </div>
            </div>

            {/* Summary Content */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="glass-dark rounded-2xl p-8 shadow-xl"
            >
              <h3 className="text-xl font-semibold text-white mb-6 flex items-center gap-2">
                <div className="w-6 h-6 bg-gradient-to-r from-green-500 to-emerald-500 rounded-full flex items-center justify-center">
                  <Heart className="w-3 h-3 text-white" />
                </div>
                Your Visit Summary
              </h3>
              
              <div className="prose prose-invert max-w-none">
                <div className="text-gray-200 leading-relaxed whitespace-pre-wrap text-lg">
                  {summaryData.summary}
                </div>
              </div>
            </motion.div>

            {/* Important Notes */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="bg-blue-900/20 border border-blue-500/30 rounded-2xl p-6"
            >
              <h4 className="text-lg font-semibold text-blue-300 mb-3">Important Information</h4>
              <ul className="space-y-2 text-blue-200 text-sm">
                <li className="flex items-start gap-2">
                  <span className="text-blue-400 mt-1">•</span>
                  This summary is provided for your convenience and understanding
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-blue-400 mt-1">•</span>
                  Please follow all instructions provided by your healthcare provider
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-blue-400 mt-1">•</span>
                  Contact your doctor's office if you have any questions or concerns
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-blue-400 mt-1">•</span>
                  Keep this summary for your medical records
                </li>
              </ul>
            </motion.div>

            {/* Footer */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.6 }}
              className="text-center py-8"
            >
              <div className="flex items-center justify-center gap-2 text-gray-400 text-sm">
                <Stethoscope className="w-4 h-4" />
                <span>Generated by Skribe - Smart Healthcare Dictation</span>
              </div>
              <p className="text-xs text-gray-500 mt-2">
                This summary was created using AI-powered medical transcription and documentation
              </p>
            </motion.div>
          </motion.div>
        )}
      </div>
    </div>
  );
}
